### ISSUE TITLE
Error on new install with no profile created

### ISSUE THREAD

**Issue by e0Re0R** [backdrop-contrib/simple_access#13]
Hi there,
On a new install of simple access, when trying to create or edit a page the following error occurs:
"Argument passed to backdrop_sort(), must be of type array, null given" for simple_access.module.

It just needs this quick fix inserted at line 623 of simple_access.module

if (empty($profiles)) {
  $profiles = array();
}

Cheers

**Comment by allsite** [comment]
I can confirm this issue.

**Comment by stpaultim** [comment]
Yes, as far as I can tell, this module is currently unusable. 

1) Install on fresh site and enable module
2) Attempt to configure any content type - /admin/structure/types/manage/card
3) Fatal Error

![image](https://user-images.githubusercontent.com/3144571/170062315-6480a7be-3fbb-4396-92cb-743f2a59a84d.png)

**Comment by stpaultim** [comment]
@herbdool - We should either get this fixed for remove from BackdropCMS.org. Right now, it pretty much makes a site unusable.

**Comment by stpaultim** [comment]
I'm working on a PR based upon the suggestion in initial post. It seems to work.

**Comment by stpaultim** [comment]
@herbdool - I've submitted a PR. I simply took the suggestion from @e0Re0R without much research, but it does seem to fix the problem. This is a pretty critical error so it would be nice to get it fixed ASAP.
